FROM golang:bookworm@sha256:4205117042f288a0112ac77ad0c7bb1df6954b010876431cc506da9aab716993 as builder

# renovate: datasource=repology depName=debian_12/git versioning=loose
ENV GIT_VER 2.39.2

# False positive in HADOLINT, the version is pinned
# hadolint ignore=DL3008
RUN apt-get update && apt-get install --no-install-recommends -y \
    "?and(?exact-name(git),?version(:${GIT_VER}))" && \
    rm -rf /var/lib/apt/lists/*

FROM builder as build

ENV CGO_ENABLED=0
RUN git clone https://github.com/maaslalani/slides.git
WORKDIR /go/slides
RUN go build

FROM alpine:3@sha256:eece025e432126ce23f223450a0326fbebde39cdf496a85d8c016293fc851978 as slides

# renovate: datasource=repology depName=alpine_3_18/chafa versioning=loose
ENV CHAFA_VER 1.12.5

RUN apk add --no-cache \
    chafa~="${CHAFA_VER}"

COPY --from=build /go/slides/slides /usr/local/bin/slides

HEALTHCHECK NONE

ENTRYPOINT ["/usr/local/bin/slides"]
