FROM golang:bookworm@sha256:5c7c2c9f1a930f937a539ff66587b6947890079470921d62ef1a6ed24395b4b3 as builder

# renovate: datasource=repology depName=debian_12/git versioning=loose
ENV GIT_VER 2.39.2

# False positive in HADOLINT, the version is pinned
# hadolint ignore=DL3008
RUN apt-get update && apt-get install --no-install-recommends -y \
    "?and(?exact-name(git),?version(:${GIT_VER}))" && \
    rm -rf /var/lib/apt/lists/*

FROM builder as build

ENV CGO_ENABLED=0
RUN git clone https://github.com/maaslalani/slides.git
WORKDIR /go/slides
RUN go build

FROM alpine:3@sha256:c5b1261d6d3e43071626931fc004f70149baeba2c8ec672bd4f27761f8e1ad6b as slides

# renovate: datasource=repology depName=alpine_3_18/chafa versioning=loose
ENV CHAFA_VER 1.12.5

RUN apk add --no-cache \
    chafa~="${CHAFA_VER}"

COPY --from=build /go/slides/slides /usr/local/bin/slides

HEALTHCHECK NONE

ENTRYPOINT ["/usr/local/bin/slides"]
