FROM golang:bookworm@sha256:8269ba28a2798bdf9ca2ecdad99ed0503c61154794fa74f0dc84e35f6b375ae3 as builder

# renovate: datasource=repology depName=debian_12/git versioning=loose
ENV GIT_VER 2.39.2

# False positive in HADOLINT, the version is pinned
# hadolint ignore=DL3008
RUN apt-get update && apt-get install --no-install-recommends -y \
    "?and(?exact-name(git),?version(:${GIT_VER}))" && \
    rm -rf /var/lib/apt/lists/*

FROM builder as build

ENV CGO_ENABLED=0
RUN git clone https://github.com/maaslalani/slides.git
WORKDIR /go/slides
RUN go build

FROM alpine:3@sha256:51b67269f354137895d43f3b3d810bfacd3945438e94dc5ac55fdac340352f48 as slides

# renovate: datasource=repology depName=alpine_3_18/chafa versioning=loose
ENV CHAFA_VER 1.12.5

RUN apk add --no-cache \
    chafa~="${CHAFA_VER}"

COPY --from=build /go/slides/slides /usr/local/bin/slides

HEALTHCHECK NONE

ENTRYPOINT ["/usr/local/bin/slides"]
