name: Push on Merge

on:
  push:
    branches:
      - main
    paths:
      - 'docker/dockerfile'
      - 'build/makefile'

jobs:
  push-changes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Run Make Push
      working-directory: ./build
      run: |
        make -f makefile push
