---
name: Push on Merge

on:
  push:
    branches:
      - main
    paths:
      - 'docker/dockerfile'
      - 'build/makefile'
  workflow_dispatch:

jobs:
  push-changes:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract Version from Makefile
        run: |
          echo "VERSION=$(grep 'VERSION :=' build/makefile | cut -d ' ' -f 3)" \
          >> "$GITHUB_ENV"

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./docker
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/ducretje/slides-image:${{ env.VERSION }}
            ghcr.io/ducretje/slides-image:latest
